routes/web.php
<?php
use Illuminate\Support\Facades\Route;
// Route::get('/', function () { return redirect('/admin/home'); });

Route::get('/', 'Guest\EventsController@index')->name('guest.home');
Route::get('pagination/fetch_data', 'Guest\EventsController@fetch_data');
Route::get('/attend/{event}', 'Guest\EventsController@index')->name('guest.home2');
Route::get('about', 'Guest\EventsController@about')->name('guest.about');
Route::get('playlist', 'Guest\EventsController@playlist')->name('guest.playlist');

//$this->get('events', 'Guest\EventsController@index')->name('events.index');
//$this->get('events/{event}', 'Guest\EventsController@show')->name('events.show');
Route::resource('events', 'Guest\EventsController');

Route::post('payment', 'Guest\PaymentsController@store')->name('guest.payment');

// Authentication Routes...
Route::get('account', 'Auth\LoginController@showLoginForm')->name('user.login');
Route::post('login', 'Auth\LoginController@login')->name('auth.login');
Route::post('register', 'Auth\RegisterController@create')->name('register');
Route::post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_passwordview');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.resetview');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset1');
Route::group(['middleware' => ['auth']], function () {
Route::resource('tickets', 'Guest\BookingController');
Route::get('tickets/confirm/{id}/{confirmed}', 'Guest\BookingController@confirm')->name('confirm-ticket');
});
Route::group(['middleware' => ['admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('events', 'Admin\EventsController');
    Route::post('events_mass_destroy', ['uses' => 'Admin\EventsController@massDestroy', 'as' => 'events.mass_destroy']);
    Route::resource('tickets', 'Admin\TicketsController');
    Route::resource('bookings', 'Admin\BookingController');
    Route::post('tickets_mass_destroy', ['uses' => 'Admin\TicketsController@massDestroy', 'as' => 'tickets.mass_destroy']);
    Route::post('bookings_mass_destroy', ['uses' => 'Admin\BookingController@massDestroy', 'as' => 'bookings.mass_destroy']);
    Route::resource('payments', 'Admin\PaymentsController');

});

app/Booking.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Payment
 *
 * @package App
 * @property string $email
 * @property string $merchant
 * @property double $amount
*/
class Booking extends Model
{
    protected $table = "bookings";
    protected $fillable = ['user_id', 'ticket_type', 'ticket_quantity', 'amount', 'phone_number', 'mpesa_code', 'event_id', 'first_name', 'last_name', 'physical_address',
    'ticket_number', 'additional_info', 'confirmed'];


    /**
     * Set attribute to date format
     * @param $input
     */
     public function event()
     {
     return $this->belongsTo('App\Event','event_id');
     }
     public function user()
          {
          return $this->belongsTo('App\User','user_id');
          }
      public function type()
        {
        return $this->belongsTo('App\Ticket','ticket_type');
        }



}

app/Http/Controllers/Admin/BookingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Booking;
use App\Event;
class BookingController extends Controller
{
public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if (! Gate::allows('booking_access')) {
                    return abort(401);
                }

                $bookings = Booking::all();

                return view('admin.bookings.index', compact('bookings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBookingRequest $request)
    {
        //
         if (! Gate::allows('booking_create')) {
                    return abort(401);
                }
         $ticket = Ticket::findOrFail($request["ticket_type"]);
//          dd($ticket);
        $request["amount"]=$request["ticket_quantity"]*$ticket->price;
        $request["ticket_number"]='ELS-'.strtoupper(uniqid());
//         $request["ticket_number"]='ELS-'.strtoupper(uniqid());
         $booking = Booking::create($request->all());
//          return redirect()->back()->withErrors('message', '');
// dd($booking);
//          return redirect('/tickets')->withErrors(['registration' => ['You have booked your ticket successfully. Please wait for the team for further instructions.']]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
       if (! Gate::allows('booking_view')) {
           return abort(401);
       }
       $booking = Booking::findOrFail($id);

       return view('admin.bookings.show', compact('booking'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        if (! Gate::allows('booking_edit')) {
                    return abort(401);
                }
//                 $events = Event::get()->pluck('title', 'id')->prepend('Please select', '');

                $booking = Booking::findOrFail($id);

                return view('admin.bookings.edit', compact('booking'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
         if (! Gate::allows('booking_edit')) {
                    return abort(401);
                }
                $booking = Booking::findOrFail($id);
                $confirmed=0;
                if($request->has("confirmed"))
                $confirmed=1;
                else
                $confirmed=0;
                $booking->update(['additional_info'=>$request->get('additional_info'),'confirmed'=>$confirmed]);
                return redirect()->route('admin.bookings.index')->with('message', 'The ticket was updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('booking_delete')) {
                    return abort(401);
                }
                $booking = Booking::findOrFail($id);
                $booking->delete();

                return redirect()->route('admin.bookings.index');
    }

    public function massDestroy(Request $request)
        {
            if (! Gate::allows('booking_delete')) {
                return abort(401);
            }
            if ($request->input('ids')) {
                $entries = Booking::whereIn('id', $request->input('ids'))->get();

                foreach ($entries as $entry) {
                    $entry->delete();
                }
            }
        }

}

app/Http/Controllers/Guest/BookingController.php
<?php

namespace App\Http\Controllers\Guest;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Guest\StoreBookingRequest;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Auth;
use App\Booking;
use App\Ticket;
class BookingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $bookings = Booking::where('user_id', Auth::user()->id)->get();

        return view('guest.tickets', compact('bookings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBookingRequest $request)
    {
        //
         if (! Gate::allows('booking_create')) {
                    return abort(401);
                }
         $ticket = Ticket::findOrFail($request["ticket_type"]);
         if($ticket->amount<=0)
         {
         return back()->withErrors(['no_tickets' => ['This type of tickets is not available. Please contact admin for help.']]);
         }
        $request["amount"]=$request["ticket_quantity"]*$ticket->price;
        $request["ticket_number"]='ELS-'.strtoupper(uniqid());
         $booking = Booking::create($request->all());
         $ticket->decrement('amount', $request["ticket_quantity"]);
         return redirect('/tickets')->withErrors(['registration' => ['You have booked your ticket successfully. Please wait for the team for further instructions.']]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        return view('guest.tickets');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function confirm($id, $confirm)
    {
    $b=Booking::findOrFail($id);
    if($confirm == 1)
    {
    return view('guest.confirm')->with('ticket',$b);
    }
    elseif($confirm == 0)
    {
    return view('guest.no_confirmed')->with('ticket',$b);
    }
    }
}

resources/views/admin/bookings/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.tickets.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.tickets.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('event_id', 'Event*', ['class' => 'control-label']) !!}
                    {!! Form::select('event_id', $events, old('event_id'), ['class' => 'form-control select2', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('event_id'))
                        <p class="help-block">
                            {{ $errors->first('event_id') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('title', 'Ticket Type*', ['class' => 'control-label']) !!}
                    {!! Form::text('title', old('title'), ['class' => 'form-control', 'placeholder' => 'Regular, Student, Early Bird etc.', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('title'))
                        <p class="help-block">
                            {{ $errors->first('title') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('amount', 'Amount of tickets available*', ['class' => 'control-label']) !!}
                    {!! Form::number('amount', old('amount'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('amount'))
                        <p class="help-block">
                            {{ $errors->first('amount') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('available_from', 'Available from*', ['class' => 'control-label']) !!}
                    {!! Form::text('available_from', old('available_from'), ['class' => 'form-control date', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('available_from'))
                        <p class="help-block">
                            {{ $errors->first('available_from') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('available_to', 'Available to*', ['class' => 'control-label']) !!}
                    {!! Form::text('available_to', old('available_to'), ['class' => 'form-control date', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('available_to'))
                        <p class="help-block">
                            {{ $errors->first('available_to') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('price', 'Price*', ['class' => 'control-label']) !!}
                    {!! Form::text('price', old('price'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('price'))
                        <p class="help-block">
                            {{ $errors->first('price') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

@section('javascript')
    @parent
    <script>
        $('.date').datepicker({
            autoclose: true,
            dateFormat: "{{ config('app.date_format_js') }}"
        });
    </script>

@stop

resources/views/admin/bookings/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.bookings.title')</h3>
    <h3 class="page-title">Ticket Number : {{$booking->ticket_number}}</h3>

    {!! Form::model($booking, ['method' => 'PUT', 'route' => ['admin.bookings.update', $booking->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_edit')
        </div>

        <div class="panel-body">

            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('title', 'Additional Information', ['class' => 'control-label']) !!}
                    {!! Form::textarea('additional_info', old('additional_info'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('additional_info'))
                        <p class="help-block">
                            {{ $errors->first('additional_info') }}
                        </p>
                    @endif
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('confirmed', 'Payment Confirmed*', ['class' => 'control-label']) !!}
                    @if($booking->confirmed)
                    <input type="checkbox" name="confirmed" checked>
                    @else
                    <input type="checkbox" name="confirmed" value="1">
                    @endif
                    <p class="help-block"></p>

                </div>
            </div>


            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/bookings/index.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.bookings.title')</h3>


    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($bookings) > 0 ? 'datatable' : '' }} @can('booking_delete') dt-select @endcan">
                <thead>
                    <tr>
                        @can('booking_delete')
                            <th style="text-align:center;"><input type="checkbox" id="select-all" /></th>
                        @endcan

                        <th>@lang('quickadmin.bookings.fields.ticket_number')</th>
                        <th>@lang('quickadmin.bookings.fields.event')</th>
                        <th>@lang('quickadmin.bookings.fields.user')</th>
                        <th>@lang('quickadmin.bookings.fields.type')</th>
                        <th>@lang('quickadmin.bookings.fields.quantity')</th>
                        <th>@lang('quickadmin.bookings.fields.amount')</th>
                        <th>@lang('quickadmin.bookings.fields.phone_number')</th>
                        <th>@lang('quickadmin.bookings.fields.mpesa_code')</th>
                        <th>@lang('quickadmin.bookings.fields.status')</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($bookings) > 0)
                        @foreach ($bookings as $booking)
                            <tr data-entry-id="{{ $booking->id }}">
                                @can('booking_delete')
                                    <td></td>
                                @endcan

                                <td>{{ $booking->ticket_number }}</td>
                                <td>{{ $booking->event->title }}</td>
                                <td>{{ $booking->user->email }}</td>
                                <td>{{ $booking->type->title }}</td>
                                <td>{{ $booking->ticket_quantity }}</td>
                                <td>{{ $booking->amount }}</td>
                                <td>{{ $booking->phone_number }}</td>
                                <td>{{ $booking->mpesa_code }}</td>
                               @if($booking->confirmed)
                              <td><span class="btn btn-success btn-xs">Paid</span></td>
                              @else
                              <td><span class="btn btn-danger btn-xs">Unpaid</span></td>
                              @endif

                                <td>
                                    @can('booking_view')
                                    <a href="{{ route('admin.bookings.show',[$booking->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('ticket_edit')
                                    <a href="{{ route('admin.bookings.edit',[$booking->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('ticket_delete')
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.bookings.destroy', $booking->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="10">@lang('quickadmin.qa_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('booking_delete')
            window.route_mass_crud_entries_destroy = '{{ route('admin.bookings.mass_destroy') }}';
        @endcan

    </script>
@endsection

resources/views/admin/bookings/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.bookings.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>


        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.bookings.fields.event')</th>
                            <td>{{ $booking->event->title }}</td>
                        </tr>
                         <tr>
                        <th>@lang('quickadmin.bookings.fields.ticket_number')</th>
                        <td>{{ $booking->ticket_number }}</td>
                    </tr>
                        <tr>
                            <th>@lang('quickadmin.bookings.fields.first_name')</th>
                           <td>{{ $booking->first_name }}</td>
                        </tr>
                        <tr>
                        <th>@lang('quickadmin.bookings.fields.last_name')</th>
                       <td>{{ $booking->last_name }}</td>
                    </tr>
                        <tr>
                            <th>@lang('quickadmin.bookings.fields.type')</th>
                              <td>{{ $booking->type->title }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.bookings.fields.quantity')</th>
                            <td>{{ $booking->ticket_quantity }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.bookings.fields.amount')</th>
                              <td>{{ $booking->amount }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.bookings.fields.phone_number')</th>
                           <td>{{ $booking->phone_number }}</td>
                        </tr>
                         <tr>
                        <th>@lang('quickadmin.bookings.fields.physical_address')</th>
                       <td>{{ $booking->physical_address }}</td>
                    </tr>
                     <tr>
                    <th>@lang('quickadmin.bookings.fields.additional_info')</th>
                   <td>{{ $booking->additional_info }}</td>
                </tr>
                <tr>
                    <th>@lang('quickadmin.bookings.fields.status')</th>
                   @if($booking->confirmed)
                   <td><span class="btn btn-success btn-sm">Paid</span></td>
                   @else
                   <td><span class="btn btn-danger btn-sm">Unpaid</span></td>
                   @endif
                </tr>
                    </table>
                </div>
            </div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.bookings.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop